version: '3.8'

services:
  caddy:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/chris-short/caddy-proxy:latest
    container_name: caddy-proxy
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./docker-entrypoint.sh:/docker-entrypoint.sh:ro
      - /home/cbshort/Container/caddy-proxy/data:/data
      - /home/cbshort/Container/caddy-proxy/config:/config
      - /home/cbshort/Container/caddy-proxy/logs:/var/log/caddy
    environment:
      - CADDY_EMAIL=chris@chrisshort.net
      - TZ=America/New_York
    restart: unless-stopped
    networks:
      - caddy-network
    security_opt:
      - no-new-privileges:true
    read_only: false  # Caddy needs to write to /data and /config
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    healthcheck:
      test: ["CMD", "caddy", "version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=caddy-proxy"
      - "maintainer=chrisshort@duck.com"

networks:
  caddy-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
